name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Efetuando o login no Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{secrets.DOCKER_HUB_PWD}}
    
      - name: Efetuando o build da imagem e envio para o Docker Hub
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            ajvideira/kube-news:latest
            ajvideira/kube-news:${{github.run_number}}
  CD:
    runs-on: ubuntu-latest

    needs: [CI]

    steps:
      - uses: actions/checkout@v3

      - name: Definindo o Kube config
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
      
      - name: Efetuando o deploy no cluster
        uses: Azure/k8s-deploy@v3.1
        with:
          images: ajvideira/kube-news:${{github.run_number}}
          manifests: k8s/deployment.yaml
